---
title: "Project #2 - Data Visualization with the Simpsons"
author: "Jonah Wiener-Brodkey"
date: "May 17, 2019"
output: html_document
---

# 1) The Visualization

### Importing the data and loading packages
```{r, eval = TRUE}
library(readr)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
simps <- na.omit(read_csv("simpsons_episodes.csv"))
```
### Manipulating the data
```{r, eval = TRUE}
simps$season <- as.factor(simps$season)

simps <- simps %>%
  group_by(season) %>%
  mutate(season_avg = mean(imdb_rating))

simps <- simps %>%
  add_count(season)
```
### Creating the graphic
```{r, eval = TRUE}
viewsbyseason <- ggplot(simps, aes(x = season, y = us_viewers_in_millions/n, fill = season_avg)) +
  geom_col() +
  labs(title = '"Simpsons" Viewers and Rating by Season',
       x = '"Simpsons" Season',
       y = "Average U.S. Viewers by Season (in millions)") +
  theme_minimal() +
  scale_x_discrete(breaks = 1:28) +
  scale_y_continuous(breaks = seq(5,25,5)) +
  scale_fill_distiller(name = "Average IMDB Rating by Season", palette = "RdYlGn", direction = 1) +
  theme(axis.text.x = element_text(size = 8),
        plot.title = element_text(size = 18))
viewsbyseason
```
